# Numpy Library

# Install library
pip install numpy
# import with aliaas:
import numpy as np

In [7]:
# Array Creation(manual)
import numpy as np
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [9]:
# 2D Array Example (Matrix): 
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3D Array Example:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Creation (Built-in Methods)

In [27]:
# Array of all zeros
array=np.zeros([1,2])
print(array)

[[0. 0.]]


In [35]:
# Array of all ones
array1=np.ones([1,2,3,4])
print(array1)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [39]:
# sequance of number
array2=np.arange(10,100,5)
print(array2)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [51]:
# Evenly spaced numbers
array4=np.linspace(0,50,5)
print(array4)

[ 0.  12.5 25.  37.5 50. ]


In [47]:
# Identity matrix
array3=np.eye(5)
print(array3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
# random values in (0,1)
array5=np.random.rand(5,5)
print(array5)

[[0.0636062  0.9172276  0.69004494 0.89748147 0.82451921]
 [0.88430131 0.096501   0.05935211 0.47607192 0.33383504]
 [0.42839729 0.35351004 0.97472868 0.58940605 0.04553159]
 [0.60442128 0.8581071  0.09847607 0.31415126 0.58960511]
 [0.59237335 0.61910418 0.21249918 0.56914288 0.42157041]]


# Array Operations & Funcation


In [56]:
# Arithmatic operation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [58]:
# multiplication
a = np.array([10,5,25])
b = np.array([44, 51, 6])
a*b

array([440, 255, 150])

In [60]:
# subtraction
a = np.array([11, 23, 39])
b = np.array([44, 5, 16])
a-b

array([-33,  18,  23])

In [64]:
# Aggregates
a=np.array([22,35,56])
a.sum()   
a.mean(), a.max(), a.min()

(37.666666666666664, 56, 22)

In [66]:
# Mathamatical
a=np.array([28,33,55])
np.sqrt(a)
np.exp(a)   
np.log(a)

array([3.33220451, 3.49650756, 4.00733319])

In [84]:
# Reshape
a=np.arange(1,25,1)
print(a)
print(a.reshape(4, 6) )


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


# matrix operations


In [102]:
# Dot product
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
D=np.dot(A,B)
T=A.T;B.T
print(T)
print(D)

[[1 3]
 [2 4]]
[[19 22]
 [43 50]]


# Indexing

In [109]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(a[1][2])    
print(a[1, 2])

60
60


In [111]:
# Boolean indexing
print(a[a > 50])

[60 70 80 90]


In [113]:
# more indexing by Own
print("First row:", a[0])
print("Second column:", a[:, 1])
print("Bottom-right element:", a[-1, -1])
rows = [0, 2]
cols = [1, 2]
print("Elements at [0,1] and [2,2]:", a[rows, cols])

First row: [10 20 30]
Second column: [20 50 80]
Bottom-right element: 90
Elements at [0,1] and [2,2]: [20 90]


# Slicing

In [116]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a[1:4])       
print(a[::2])     
print(a[-3:]) 

[20 30 40]
[10 30 50]
[40 50 60]


In [118]:
b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(b[0:2, 1:3])
print(b[::2, ::2])
print(b[-1, -2:]) 

[[2 3]
 [6 7]]
[[ 1  3]
 [ 9 11]]
[11 12]
